# Generated by Django 2.0.7 on 2019-07-02 03:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20190701_2203'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='id',
            new_name='id_products',
        ),
    ]
